version: '3'

services:
  # Serviço de sessão do WhatsApp (você pode criar múltiplos destes com nomes diferentes)
  whatsapp-session:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whatsapp-session
    restart: always
    ports:
      - "1234:1234"
    volumes:
      - whatsapp-data:/app/data
    environment:
      - PORT=1234
      - SESSION_ID=whatsapp-session-1
      - SESSION_DIR=/app/data/sessions
      - DEBUG=false
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - RABBITMQ_OUTBOUND_QUEUE=zapbless.outbound
      - RABBITMQ_INBOUND_QUEUE=zapbless.inbound
      - CHURCH_ID=${CHURCH_ID:-default-church}
    depends_on:
      - rabbitmq
    networks:
      - whatsapp-network

  # Serviço RabbitMQ para mensageria
  rabbitmq:
    image: rabbitmq:3-management
    container_name: whatsapp-rabbitmq
    restart: always
    ports:
      - "5672:5672"   # Porta AMQP
      - "15672:15672" # Porta de gerenciamento
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=zapbless
      - RABBITMQ_DEFAULT_PASS=zapbless
    networks:
      - whatsapp-network

networks:
  whatsapp-network:
    driver: bridge

volumes:
  whatsapp-data:
  rabbitmq-data: 